export const SET_COMMENT = 'SET_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_CHILD_COMMENT = 'DELETE_CHILD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const REPLY_COMMENT = 'REPLY_COMMENT';